In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd

In [2]:
base_dir = '../../sample_data/codebench/2024/'

In [10]:
assignments = pd.read_csv(base_dir + 'LinkTables/Assignment.csv')
assignments.head()

   AssignmentID                                           URL
0      19988101   ./output\Resources\Assignment\19988101.yaml
1      58552358   ./output\Resources\Assignment\58552358.yaml
2      69717310   ./output\Resources\Assignment\69717310.yaml
3     119249144  ./output\Resources\Assignment\119249144.yaml
4     216359026  ./output\Resources\Assignment\216359026.yaml

In [13]:
import yaml

def get_assignment_cols(url):
    url = url.replace('./output', base_dir)
    data = yaml.safe_load(open(url))
    print(data)

get_assignment_cols(assignments.URL.iloc[0])

{'assessment-title': 'Lab 1 - Variáveis e Estrutura Sequencial', 'class-name': 'Introdução à Ciência dos Computadores', 'class-number': 2607741091, 'start': datetime.datetime(2024, 8, 29, 0, 0), 'end': datetime.datetime(2024, 9, 25, 23, 55), 'language': {'name': 'Python', 'version': '3.8.5'}, 'type': 'assignment', 'weight': 1, 'exercises': {'total': 10, 'ids': [48684178, 1462915504, 1626817775, 1719669876, 2132966528, 2819779400, 3455942218, 3691284457, 3921830315, 4233865845]}}

In [7]:
grades = pd.read_csv(base_dir + 'LinkTables/AssignmentSubject.csv')

In [8]:
grades

,AssignmentID,SubjectID,URL
0,19988101,153511603,./output\Resources\Grades\19988101_153511603.yaml
1,19988101,267632557,./output\Resources\Grades\19988101_267632557.yaml
2,19988101,278108244,./output\Resources\Grades\19988101_278108244.yaml
3,19988101,280846303,./output\Resources\Grades\19988101_280846303.yaml
4,19988101,367011683,./output\Resources\Grades\19988101_367011683.yaml
...,...,...,...
3480,4270670054,3722837204,./output\Resources\Grades\4270670054_372283720...
3481,4270670054,4049235421,./output\Resources\Grades\4270670054_404923542...
3482,4270670054,4109659188,./output\Resources\Grades\4270670054_410965918...
3483,4270670054,4167959796,./output\Resources\Grades\4270670054_416795979...
3484,4270670054,4249845735,./output\Resources\Grades\4270670054_424984573...

In [9]:
import yaml

def get_grade_columns(url):
    url = url.replace('./output', base_dir)
    data = yaml.safe_load(open(url))
    print(data)

get_grade_columns(grades.URL.iloc[0])

{'grade': 10.0, 'number-of-exercises': 10, 'correct': 10, 'incorrect': 0, 'blank': 0}